receive_and_transmit: receive_and_transmit.o
	$(CC) $(LDFLAGS) -g receive_and_transmit.o -o receive_and_transmit
receive_and_transmit.o: receive_and_transmit.c
	$(CC) $(CFLAGS) -g -c receive_and_transmit.c

clean:
	rm *.o receive_and_transmit
